# Generated by Django 4.1.3 on 2022-11-26 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 9, 56, 36, 694895)),
        ),
        migrations.AlterField(
            model_name='clinreport',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 9, 56, 36, 696888)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 9, 56, 36, 693898)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 9, 56, 36, 695891)),
        ),
        migrations.AlterField(
            model_name='laborposition',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 9, 56, 36, 695891)),
        ),
    ]
