# Generated by Django 4.1.3 on 2022-11-27 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_attachments_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 20, 52, 24, 89684)),
        ),
        migrations.AlterField(
            model_name='clinreport',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 20, 52, 24, 91678)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 20, 52, 24, 88687)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 20, 52, 24, 90680)),
        ),
        migrations.AlterField(
            model_name='laborposition',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 20, 52, 24, 90680)),
        ),
    ]
