# Generated by Django 4.1.3 on 2022-11-27 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_attachments_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 22, 27, 34, 539654)),
        ),
        migrations.AlterField(
            model_name='clinreport',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 22, 27, 34, 541651)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 22, 27, 34, 538659)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 22, 27, 34, 540650)),
        ),
        migrations.AlterField(
            model_name='laborposition',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 11, 26, 22, 27, 34, 540650)),
        ),
    ]
